### PR TITLE
Implement basic plugin functionality

### LINKED ISSUE #3: Implement basic functionality
Plugin should replace `$stub$` with file revision number. It should be covered by tests.

### PR DESCRIPTION
**Pull request by gvlasov**
Implement getting version number for a file and writing that version number to that file during `git-version-insert:insert-version` goal.

Fixes #3

### CODE REVIEW

**Comment by Suseika** [comment]
@rultor merge

**Comment by Suseika** [comment]
@rultor merge

**Comment by Suseika** [comment]
@rultor merge

**Comment by Suseika** [comment]
@rultor merge

**Comment by gvlasov** [comment]
@rultor merge

**Pull request merged**
